/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyzerTest;

public class MoodAnalyzer 
{
	public String analyseMethod(String mood)
	{
		if(mood.contains("sad"))
			return "sad";
		return "happy" ;
	}
}

